name: build apk
on:
  repository_dispatch:
    types: build-apk
  
jobs:
    build-app:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Get most recent Conversations commit
        id: commit
        uses: actions/checkout@v2
        with:
          repository: 'iNPUTmice/Conversations'
          path: ./conv-commit-check

      - name: Get version id and commit; write new values (not saved unless workflow is a success)
        id: version
        run: |
          bash -c "echo -n $(($(cat .github/CONVAUTO_VERSION) + 1))" > .github/CONVAUTO_VERSION
          echo "::set-output name=conv-auto-version::$(cat .github/CONVAUTO_VERSION)"
          echo "::set-output name=conv-auto-commit::$(cat .github/CONVAUTO_COMMIT)"
          bash -c "echo $(git -C conv-commit-check rev-parse --short --verify HEAD)" > .github/CONVAUTO_COMMIT
          echo "::set-output name=date-long::$(date '+%B %d, %Y')"     

      - uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            ~/.android/debug.keystore
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Conv Auto
        uses: docker://tyler71/convauto:latest
        env:
          CONV_NAME: ConvAuto
          CONV_ID: convauto
          CONV_VERSION: ${{ steps.version.outputs.conv-auto-version }}
        with:
          args: "master"

      - name: Find Universal apk
        id: apk-location
        run: |
          echo "::set-output name=universal-apk::$(find -type f -iname '*-universal-*.apk' -print -quit)"
          echo "::set-output name=apk-commit::$(git -C ./Conversations rev-parse --short --verify HEAD)"
          echo "::set-output name=apk-commit-msg::$(git -C ./Conversations log -1 --pretty='%B')"       

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: conv_${{ steps.apk-location.outputs.apk-commit }}
          release_name: Conversations - ${{ steps.version.outputs.date-long }} [${{ steps.apk-location.outputs.apk-commit }}]
          body: ${{ steps.apk-location.outputs.apk-commit-msg }}
          draft: true
          prerelease: false

      - name: Upload Compiled Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.apk-location.outputs.universal-apk }}
          asset_name: Conversations-AutoBuild.apk
          asset_content_type: application/apk

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_AUTH_TOKEN }} # Auth token will let gh-pages workflow trigger
        with:
          continue_on_error: true
          release_id: ${{ steps.create_release.outputs.id }}

      - name: Rollback Release # if tag already exists
        if: failure()
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.create_release.id }}
          # Using a tag name
          tag: conv_${{ steps.apk-location.outputs.apk-commit }}
          # Always delete the tag, even if a release is not associated with it.
          always_delete_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version count
        if: success()
        uses: alexesprit/action-update-file@master
        with:
          file-path: .github/CONVAUTO_VERSION
          commit-msg: Increment debug version to ${{ steps.version.outputs.conv-auto-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version commit
        if: success()
        uses: alexesprit/action-update-file@master
        with:
          file-path: .github/CONVAUTO_COMMIT
          commit-msg: Update apk to ${{ steps.apk-location.outputs.apk-commit }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
