name: build apk
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * *'
  
jobs:
    build-app:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        
      - name: Get version id
        id: version
        run: |
          echo "::set-output name=conv-auto-version::$(cat docker/CONVAUTO_VERSION)"
          bash -c "$(($(cat docker/CONVAUTO_VERSION) + 1)) > docker/CONVAUTO_VERSION"

      - name: Build Conv Auto
        uses: docker://tyler71/convauto:latest
        env:
          CONV_NAME: ConvAuto
          CONV_ID: convauto
          CONV_VERSION: ${{ steps.version.outputs.conv-auto-version }}
        with:
          args: "master"
          
      - run: find .

      - name: Find Universal apk
        id: apk-location
        run: |
          echo "::set-output name=universal-apk::$(find -type f -iname '*-universal-*.apk' -print -quit)"
          echo "::set-output name=apk-commit::$(git -C ./Conversations rev-parse --short --verify HEAD)"
          echo "::set-output name=apk-commit-msg::$(git -C ./Conversations log -1 --pretty='%B')"

      - name: Get current date
        id: current-date
        run: |
          echo "::set-output name=date-slug::$(date '+%m-%d-%Y')"
          echo "::set-output name=date-long::$(date '+%B %d, %Y')"          

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: conv_${{ steps.apk-location.outputs.apk-commit }}
          release_name: Conversations - ${{ steps.current-date.outputs.date-long }} [${{ steps.apk-location.outputs.apk-commit }}]
          body: ${{ steps.apk-location.outputs.apk-commit-msg }}
          draft: true
          prerelease: false

      - name: Upload Compiled Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ steps.apk-location.outputs.universal-apk }}
          asset_name: Conversations-AutoBuild.apk
          asset_content_type: application/apk

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_AUTH_TOKEN }} # Auth token will let gh-pages workflow trigger
        with:
          release_id: ${{ steps.create_release.outputs.id }}

      - name: Rollback Release # if tag already exists
        if: failure()
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          id: ${{ steps.create_release }}
          # Using a tag name
          tag: conv_${{ steps.apk-location.outputs.apk-commit }}
          # Always delete the tag, even if a release is not associated with it.
          always_delete_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version count
        uses: alexesprit/action-update-file@master
        with:
          file-path: docker/CONVAUTO_VERSION
          commit-msg: Increment debug version
          github-token: ${{ secrets.GITHUB_TOKEN }}
